
package form;
import form.CambiaPanel;
import java.awt.Panel;
import form.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import Main.*;
import java.awt.FontFormatException;
import java.awt.Window;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
/**
 *
 * @author ross
 */
public class PnlAddInventario extends javax.swing.JPanel {
    Main m;

    /**
     * Creación de nuevo panel
     */
    public PnlAddInventario() throws FontFormatException {
        m =new Main();
        initComponents();
    }

    public PnlAddInventario(ActionListener actionListener) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clickAmplificador = new javax.swing.JLabel();
        labelLaptop = new javax.swing.JLabel();
        labelBocina = new javax.swing.JLabel();
        click_proyectores = new javax.swing.JLabel();
        amplificador = new javax.swing.JLabel();
        laptop = new javax.swing.JLabel();
        proyectores = new javax.swing.JLabel();
        bocina = new javax.swing.JLabel();

        setBackground(new java.awt.Color(246, 246, 246));
        setName("panelBodyAddInventario"); // NOI18N

        clickAmplificador.setBackground(new java.awt.Color(201, 116, 29));
        clickAmplificador.setForeground(new java.awt.Color(206, 74, 74));
        clickAmplificador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/speaker.png"))); // NOI18N
        clickAmplificador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickAmplificadorMouseClicked(evt);
            }
        });

        labelLaptop.setBackground(new java.awt.Color(201, 116, 29));
        labelLaptop.setForeground(new java.awt.Color(206, 74, 74));
        labelLaptop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/lapTop.png"))); // NOI18N
        labelLaptop.setText("jLabel1");
        labelLaptop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLaptopMouseClicked(evt);
            }
        });

        labelBocina.setBackground(new java.awt.Color(201, 116, 29));
        labelBocina.setForeground(new java.awt.Color(206, 74, 74));
        labelBocina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/bocina.png"))); // NOI18N
        labelBocina.setText("jLabel1");
        labelBocina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBocinaMouseClicked(evt);
            }
        });

        click_proyectores.setBackground(new java.awt.Color(201, 116, 29));
        click_proyectores.setForeground(new java.awt.Color(206, 74, 74));
        click_proyectores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/projector.png"))); // NOI18N
        click_proyectores.setText("jLabel1");
        click_proyectores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                click_proyectoresMouseClicked(evt);
            }
        });

        amplificador.setFont(new java.awt.Font("Roboto Lt", 1, 18)); // NOI18N
        amplificador.setText("Amplificadores");

        laptop.setFont(new java.awt.Font("Roboto Lt", 1, 18)); // NOI18N
        laptop.setText("Laptop");

        proyectores.setFont(new java.awt.Font("Roboto Lt", 1, 18)); // NOI18N
        proyectores.setText("Proyectores");

        bocina.setFont(new java.awt.Font("Roboto Lt", 1, 18)); // NOI18N
        bocina.setText("Bocina");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(click_proyectores, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(proyectores))
                    .addComponent(clickAmplificador, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(amplificador)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelLaptop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(laptop)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(bocina))
                        .addComponent(labelBocina, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(175, 175, 175))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelBocina, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(bocina))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clickAmplificador, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(amplificador)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(click_proyectores, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(proyectores)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(laptop)
                        .addGap(41, 41, 41))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void clickAmplificadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickAmplificadorMouseClicked
        try {
            // TODO add your
            //PnlAddAmplificador pnl = new PnlAddAmplificador();
            //this.m.panelBody.add(pnl);
            //m.show();

            new CambiaPanel(m.panelBody, new form.PnlAddAmplificador());
        } catch (FontFormatException ex) {
            Logger.getLogger(PnlAddInventario.class.getName()).log(Level.SEVERE, null, ex);
        }
        m.show(true);
        
    }//GEN-LAST:event_clickAmplificadorMouseClicked

    private void labelBocinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBocinaMouseClicked
        // TODO add your handling code here:
        new CambiaPanel(m.panelBody, new form.PnlAddBocina());
        m.show(true);
        
    }//GEN-LAST:event_labelBocinaMouseClicked

    private void click_proyectoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_click_proyectoresMouseClicked
        // TODO add your handling code here:
        new CambiaPanel(m.panelBody, new form.PnlAddProyector());
        m.show(true);
    }//GEN-LAST:event_click_proyectoresMouseClicked

    private void labelLaptopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLaptopMouseClicked
        // TODO add your handling code here:
        new CambiaPanel(m.panelBody, new form.PnlAddLap());
        m.show(true);
    }//GEN-LAST:event_labelLaptopMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amplificador;
    private javax.swing.JLabel bocina;
    public javax.swing.JLabel clickAmplificador;
    private javax.swing.JLabel click_proyectores;
    public javax.swing.JLabel labelBocina;
    private javax.swing.JLabel labelLaptop;
    private javax.swing.JLabel laptop;
    private javax.swing.JLabel proyectores;
    // End of variables declaration//GEN-END:variables
}
