package form;

import form.CambiaPanel;
import Main.Main;
import java.awt.Window;
import java.awt.event.ActionListener;
import javax.swing.SwingUtilities;
import Fonts.Fuentes;
import java.awt.FontFormatException;
import java.util.List;
import javax.swing.JOptionPane;
import api.ClienteEquipos;
import models.Equipo;

/**
 *
 * @author ross
 */
public class PnlAddAmplificador extends javax.swing.JPanel {

    private Equipo equipo;
    private ClienteEquipos api;

    Fuentes tipoDeFuente;

    /**
     * Creación de nuevo panel
     */
    public PnlAddAmplificador() throws FontFormatException {
        initComponents();
        equipo = new Equipo();
        api = new ClienteEquipos();
        tipoDeFuente = new Fuentes();
        jLabelDetalle.setFont(tipoDeFuente.fuente(tipoDeFuente.quicSemiBold, 0, 19));
        jLabelAgregarAmplificador.setFont(tipoDeFuente.fuente(tipoDeFuente.quicSemiBold, 0, 14));
        jLabelNumSerie.setFont(tipoDeFuente.fuente(tipoDeFuente.quickBold, 0, 18));

    }

    PnlAddAmplificador(ActionListener actionListener) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAgregarAmplificador = new javax.swing.JLabel();
        jLabelDetalle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelNumSerie = new javax.swing.JLabel();
        btnCerrar = new rsbuttom.RSButtonMetro();
        btnAddAmplificador = new rsbuttom.RSButtonMetro();
        txtFieldSerie = new javax.swing.JTextField();

        setBackground(new java.awt.Color(246, 246, 246));

        jLabelAgregarAmplificador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/add.png"))); // NOI18N
        jLabelAgregarAmplificador.setText("Agregar Amplificador");
        jLabelAgregarAmplificador.setIconTextGap(10);

        jLabelDetalle.setFont(new java.awt.Font("Roboto Lt", 1, 15)); // NOI18N
        jLabelDetalle.setText("Detalles del Dispositivo");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/amplifier128.png"))); // NOI18N

        jLabelNumSerie.setFont(new java.awt.Font("Roboto Lt", 1, 18)); // NOI18N
        jLabelNumSerie.setText("Número de Serie");

        btnCerrar.setText("Cancelar");
        btnCerrar.setColorNormal(new java.awt.Color(116, 210, 129));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnAddAmplificador.setText("Agregar");
        btnAddAmplificador.setColorNormal(new java.awt.Color(116, 210, 129));
        btnAddAmplificador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAmplificadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabelDetalle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddAmplificador, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelNumSerie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFieldSerie)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabelAgregarAmplificador, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelAgregarAmplificador, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDetalle)
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddAmplificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNumSerie)
                        .addGap(18, 18, 18)
                        .addComponent(txtFieldSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        Window pnl = SwingUtilities.getWindowAncestor(PnlAddAmplificador.this);
        pnl.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnAddAmplificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAmplificadorActionPerformed
        if (!"".equals(txtFieldSerie.getText())) {
            equipo.setIdTipoEquipo(5);
            equipo.setIdEquipo(getLastId());
            equipo.setSerial(txtFieldSerie.getText().toUpperCase());
            if (api.insert(equipo) != null) {
                JOptionPane.showMessageDialog(null, "Agregado con éxito");
            } else {
                JOptionPane.showMessageDialog(null, "Error al agregar");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe incluir un serial");
        }
    }//GEN-LAST:event_btnAddAmplificadorActionPerformed

    private int getLastId() {
        int id = 0;
        List<Equipo> all = api.getAll();
        for (Equipo equipo1 : all) {
            if (id < equipo1.getIdEquipo()) {
                id = equipo1.getIdEquipo();
            }
        }
        id++;
        return id;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro btnAddAmplificador;
    private rsbuttom.RSButtonMetro btnCerrar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAgregarAmplificador;
    private javax.swing.JLabel jLabelDetalle;
    private javax.swing.JLabel jLabelNumSerie;
    private javax.swing.JTextField txtFieldSerie;
    // End of variables declaration//GEN-END:variables
}
