package form;

import Fonts.Fuentes;
import com.placeholder.PlaceHolder;

import java.awt.FontFormatException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import api.ClienteEquipos;
import models.Equipo;

public class PnlTiposDeInventario extends javax.swing.JPanel {

    Fuentes tipoDeFuentes;
    private ClienteEquipos api;
    private DefaultTableModel modelo;
    /**
     * Creates new form Panel1
     */
    PlaceHolder holder;

    public PnlTiposDeInventario() throws FontFormatException {
        initComponents();
        modelo = new DefaultTableModel();
        tipoDeFuentes = new Fuentes();
        modelo.setColumnIdentifiers(new Object[]{"ID", "TIPO EQUIPO", "SERIAL", "ESTADO"});
        tablaSolicitudes.setModel(modelo);
        tablaSolicitudes.setFont(tipoDeFuentes.fuente(tipoDeFuentes.quickMedium, 0, 15));
        jLabelSolicitudesPrestamos.setFont(tipoDeFuentes.fuente(tipoDeFuentes.quickBold, 0, 17));
        api = new ClienteEquipos();
        getInventario();

        lId.setVisible(false);
        txtId.setVisible(false);
        btnDelete.setVisible(false);
    }

    public void holders() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelSolicitudesPrestamos = new javax.swing.JLabel();
        pnlDatosIngresar = new javax.swing.JPanel();
        txtBuscarPorSerialEnLista = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnDelete = new rsbuttom.RSButtonMetro();
        btnListar = new rsbuttom.RSButtonMetro();
        btnEliminar = new rsbuttom.RSButtonMetro();
        btnEditar1 = new rsbuttom.RSButtonMetro();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaSolicitudes = new javax.swing.JTable();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(java.awt.Color.white);

        jLabelSolicitudesPrestamos.setBackground(new java.awt.Color(127, 145, 232));
        jLabelSolicitudesPrestamos.setFont(new java.awt.Font("Roboto Lt", 1, 18)); // NOI18N
        jLabelSolicitudesPrestamos.setForeground(java.awt.Color.white);
        jLabelSolicitudesPrestamos.setText("                                                                     Inventario en existencia");
        jLabelSolicitudesPrestamos.setOpaque(true);

        pnlDatosIngresar.setBackground(new java.awt.Color(255, 255, 255));
        pnlDatosIngresar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscarPorSerialEnLista.setBackground(new java.awt.Color(226, 216, 216));
        txtBuscarPorSerialEnLista.setBorder(null);
        pnlDatosIngresar.add(txtBuscarPorSerialEnLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 200, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/barraBusqueda.png"))); // NOI18N
        jLabel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jLabel1KeyTyped(evt);
            }
        });
        pnlDatosIngresar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, 41));

        lId.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lId.setText("ID");
        pnlDatosIngresar.add(lId, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 50, -1));
        pnlDatosIngresar.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 92, -1));

        btnDelete.setText("Confirmar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        pnlDatosIngresar.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 90, 26));

        btnListar.setText("Actualizar lista");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        pnlDatosIngresar.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, 26));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        pnlDatosIngresar.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, 26));

        btnEditar1.setText("Editar");
        btnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar1ActionPerformed(evt);
            }
        });
        pnlDatosIngresar.add(btnEditar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 130, 26));

        jScrollPane1.setBackground(java.awt.Color.white);
        jScrollPane1.setBorder(null);
        jScrollPane1.setToolTipText("");

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        tablaSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Tipo de Equipo", "Serial", "Entradal"
            }
        ));
        tablaSolicitudes.setRowHeight(25);
        tablaSolicitudes.setRowSelectionAllowed(false);
        tablaSolicitudes.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jScrollPane2.setViewportView(tablaSolicitudes);

        jLayeredPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(287, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jLayeredPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSolicitudesPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlDatosIngresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelSolicitudesPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDatosIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (txtId.getText() != "") {
            if (api.deleteOne(Equipo.class, Integer.parseInt(txtId.getText())) != null) {
                JOptionPane.showMessageDialog(null, "Eliminado con éxito registro con Id:" + txtId.getText());
                esconderData();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese un id válido");
        }


    }//GEN-LAST:event_btnDeleteActionPerformed

    private void esconderData(){
        txtId.setText("");
        lId.setVisible(false);
        txtId.setVisible(false);
        btnDelete.setVisible(false);
        
    }
    
    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        cleanTable();
        getInventario();

    }//GEN-LAST:event_btnListarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        lId.setVisible(true);
        txtId.setVisible(true);
        btnDelete.setVisible(true);

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditar1ActionPerformed

    private void jLabel1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1KeyTyped

    private void getInventario() {
        List<Equipo> listaEquipos = api.getAll();
        for (Equipo e : listaEquipos) {
            modelo.addRow(new Object[]{e.getIdEquipo(), setTipoEquipo(e.getIdTipoEquipo()), e.getSerial(), e.getEstado().toUpperCase()});
        }
    }

    private String setTipoEquipo(int tipo) {
        String myTipo = "";
        switch (tipo) {
            case 1:
                myTipo = "PROYECTOR HDMI";
                break;
            case 2:
                myTipo = "PROYECTOR VGA";
                break;
            case 3:
                myTipo = "LAPTOP";
                break;
            case 4:
                myTipo = "BOCINA";
                break;
            case 5:
                myTipo = "AMPLIFICADOR";
                break;
        }
        return myTipo;
    }

    private void cleanTable() {
        modelo.setRowCount(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro btnDelete;
    private rsbuttom.RSButtonMetro btnEditar1;
    private rsbuttom.RSButtonMetro btnEliminar;
    private rsbuttom.RSButtonMetro btnListar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelSolicitudesPrestamos;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel lId;
    private javax.swing.JPanel panelLista;
    private javax.swing.JPanel panelLista1;
    private javax.swing.JPanel panelLista2;
    private javax.swing.JPanel pnlDatosIngresar;
    private javax.swing.JTable tablaSolicitudes;
    private javax.swing.JTable tablaSolicitudes1;
    private javax.swing.JTable tablaSolicitudes2;
    private javax.swing.JTable tablaSolicitudes3;
    private javax.swing.JTextField txtBuscarPorSerialEnLista;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables

}
